---
repository:
    name: infra-landing-zone
    description: Landing zone for makemyinfra.cloud and other stuffs
    topics: example, devops, tooling, ecs, sre, cli
    default_branch: main
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: true
    delete_branch_on_merge: true
    has_projects: true
    has_wiki: false
    enable_vulnerability_alerts: true
    enable_automated_security_fixes: true
    teams:
        - name: maintainers
          permission: admin
        - name: contributors
          permission: push
labels:
    - name: bug
      color: CC0000
      description: Something is not working fine ğŸ›.
    - name: feature
      color: '#336699'
      description: New functionality ğŸš€.
    - name: Help Wanted
      new_name: help wanted ğŸ™
    - name: documentation
      color: 0075ca
      description: Improvements or additions to documentation ğŸ“š.
branches:
    - name: main
      protection:
          required_pull_request_reviews:
              required_approving_review_count: 1
              dismiss_stale_reviews: true
              require_code_owner_reviews: true
              dismissal_restrictions: {}
              code_owner_approval: true
              required_conversation_resolution: true
          required_status_checks:
              strict: true
              contexts:
                  - DCO
          enforce_admins: false
          required_linear_history: true
          restrictions:
              users: [Excoriate]
              apps: []
              teams: []
